# Generated by Django 5.2.1 on 2025-05-11 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_teacherprofile_subjects_taught'),
        ('school_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('SENT', 'Đã gửi'), ('READ', 'Đã xem'), ('ARCHIVED', 'Đã lưu trữ')], default='DRAFT', max_length=10, verbose_name='Trạng thái')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian gửi dự kiến')),
                ('is_published', models.BooleanField(default=False, verbose_name='Đã phát hành')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
                ('target_classes', models.ManyToManyField(blank=True, related_name='class_notifications', to='school_data.class', verbose_name='Gửi đến Lớp học')),
                ('target_roles', models.ManyToManyField(blank=True, related_name='role_notifications', to='accounts.role', verbose_name='Gửi đến Vai trò')),
                ('target_users', models.ManyToManyField(blank=True, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận cụ thể')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Các Thông báo',
                'ordering': ['-created_time'],
            },
        ),
    ]
