# Generated by Django 5.2.1 on 2025-05-11 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề cuộc hội thoại (cho nhóm)')),
                ('conversation_type', models.CharField(choices=[('DIRECT', 'Trò chuyện trực tiếp (1-1)'), ('GROUP', 'Trò chuyện nhóm')], default='DIRECT', max_length=10, verbose_name='Loại cuộc hội thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên tham gia')),
            ],
            options={
                'verbose_name': 'Cuộc hội thoại',
                'verbose_name_plural': 'Các Cuộc hội thoại',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation', verbose_name='Thuộc cuộc hội thoại')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages_in_conversation', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Các Tin nhắn',
                'ordering': ['sent_at'],
            },
        ),
    ]
