# Generated by Django 5.2.1 on 2025-05-11 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_subjects_taught'),
        ('communications', '0002_conversation_message'),
        ('school_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('LEAVE_APPLICATION', 'Đơn xin nghỉ học'), ('GRADE_APPEAL', 'Đơn phúc khảo điểm'), ('GENERAL_REQUEST', 'Kiến nghị/Đề xuất chung'), ('FEEDBACK', 'Góp ý')], max_length=50, verbose_name='Loại đơn')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề đơn/kiến nghị')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Mới gửi'), ('PROCESSING', 'Đang xử lý'), ('RESOLVED', 'Đã giải quyết'), ('REJECTED', 'Đã từ chối'), ('CLOSED', 'Đã đóng')], default='SUBMITTED', max_length=20, verbose_name='Trạng thái')),
                ('response_content', models.TextField(blank=True, null=True, verbose_name='Nội dung phản hồi từ nhà trường')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phản hồi')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_request_forms', to='school_data.department', verbose_name='Phòng Ban xử lý')),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_request_forms', to='accounts.studentprofile', verbose_name='Học sinh liên quan (nếu có)')),
                ('responded_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_request_forms', to=settings.AUTH_USER_MODEL, verbose_name='Người phản hồi')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_forms', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Đơn từ/Kiến nghị',
                'verbose_name_plural': 'Các Đơn từ/Kiến nghị',
                'ordering': ['-submission_date'],
            },
        ),
    ]
