# Generated by Django 5.2.1 on 2025-05-12 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_requestform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__name': 'TEACHER'}, related_name='received_request_forms', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên xử lý/nhận đơn'),
        ),
    ]
