# Generated by Django 5.2.1 on 2025-05-11 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên Phòng Ban')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Phòng Ban')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Phòng Ban',
                'verbose_name_plural': 'Các Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tên Môn học')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả Môn học')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Các Môn học',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Lớp học')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True, verbose_name='Năm học (VD: 2024-2025)')),
                ('homeroom_teacher', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên Chủ nhiệm')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Các Lớp học',
                'unique_together': {('name', 'academic_year')},
            },
        ),
    ]
