# Generated by Django 5.2.1 on 2025-05-11 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parentprofile_studentprofile_teacherprofile'),
        ('school_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_data.class', verbose_name='Lớp Hiện Tại'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.parentprofile', verbose_name='Phụ Huynh Chính'),
        ),
    ]
