# Generated by Django 5.2.1 on 2025-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_current_class_studentprofile_parent'),
        ('school_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='school_data.subject', verbose_name='Các Môn học Giảng dạy'),
        ),
    ]
