# Generated by Django 5.2.1 on 2025-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_subjects_taught'),
        ('school_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_subjects',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='school_data.subject', verbose_name='Các Môn học Đã đăng ký/Học'),
        ),
    ]
