# Generated by Django 5.2.1 on 2025-05-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_enrolled_subjects'),
        ('school_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='school_data.department', verbose_name='Phòng Ban Công tác (nếu có)'),
        ),
    ]
