# Generated by Django 5.2.1 on 2025-05-11 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_teacherprofile_subjects_taught'),
        ('school_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('CONDUCT', 'Đánh giá Hạnh kiểm'), ('SUBJECT_REVIEW', 'Nhận xét Môn học'), ('TERM_REVIEW', 'Đánh giá Cuối kỳ/Năm')], max_length=30, verbose_name='Loại đánh giá')),
                ('evaluation_date', models.DateField(verbose_name='Ngày đánh giá')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá/nhận xét')),
                ('evaluator', models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['TEACHER', 'SCHOOL_ADMIN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.studentprofile', verbose_name='Học sinh được đánh giá')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_evaluations', to='school_data.subject', verbose_name='Môn học (nếu có)')),
            ],
            options={
                'verbose_name': 'Đánh giá/Nhận xét',
                'verbose_name_plural': 'Các Đánh giá/Nhận xét',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='RewardAndDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('REWARD', 'Khen thưởng'), ('DISCIPLINE', 'Kỷ luật')], max_length=10, verbose_name='Loại (Khen thưởng/Kỷ luật)')),
                ('date_issued', models.DateField(verbose_name='Ngày quyết định')),
                ('reason', models.TextField(verbose_name='Nội dung/Lý do')),
                ('issued_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_rewards_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Người ra quyết định')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_discipline_records', to='accounts.studentprofile', verbose_name='Học sinh')),
            ],
            options={
                'verbose_name': 'Khen thưởng/Kỷ luật',
                'verbose_name_plural': 'Các mục Khen thưởng/Kỷ luật',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Điểm số')),
                ('exam_type', models.CharField(choices=[('MID_TERM_1', 'Giữa Học kỳ 1'), ('END_TERM_1', 'Cuối Học kỳ 1'), ('MID_TERM_2', 'Giữa Học kỳ 2'), ('END_TERM_2', 'Cuối Học kỳ 2'), ('FINAL_EXAM', 'Thi Tốt nghiệp (Nếu có)'), ('ORAL_TEST', 'Kiểm tra miệng'), ('15_MIN_TEST', 'Kiểm tra 15 phút'), ('45_MIN_TEST', 'Kiểm tra 1 tiết (45 phút)')], max_length=20, verbose_name='Loại kỳ thi/kiểm tra')),
                ('exam_date', models.DateField(verbose_name='Ngày thi/kiểm tra')),
                ('academic_period', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kỳ học/Năm học (VD: HK1 2024-2025)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú (nếu có)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accounts.studentprofile', verbose_name='Học sinh')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school_data.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Điểm số',
                'verbose_name_plural': 'Các Điểm số',
                'ordering': ['-exam_date', 'subject'],
                'unique_together': {('student', 'subject', 'exam_type', 'exam_date', 'academic_period')},
            },
        ),
    ]
